"""
propagate HP tag from majority-HP barcode to all reads sharing the same BX.

input:  SAM stream on stdin
output: SAM stream on stdout
args:   --map  tsv  (BX<TAB>HP) generated by upstream awk pass

usage:
    samtools view -h in.bam \
        | python3 propagate_bx_hp.py --map bx_hp.tsv \
        | samtools view -bS - > out.bam
"""
import sys
import argparse

ap = argparse.ArgumentParser()
ap.add_argument("--map", required=True, help="tsv: BX<TAB>HP(1|2)")
args = ap.parse_args()

bx2hp = {}
with open(args.map) as f:
    for line in f:
        parts = line.rstrip("\n").split("\t")
        if len(parts) >= 2 and parts[1] in ("1", "2"):
            bx2hp[parts[0]] = parts[1]

write = sys.stdout.write
for line in sys.stdin:
    if line.startswith("@"):
        write(line)
        continue
    fields = line.rstrip("\n").split("\t")
    bx = None
    hp_idx = -1
    for i in range(11, len(fields)):
        f = fields[i]
        if f.startswith("BX:Z:"):
            bx = f[5:]
        elif f.startswith("HP:i:"):
            hp_idx = i
    if bx and bx in bx2hp:
        new_tag = "HP:i:" + bx2hp[bx]
        if hp_idx >= 0:
            fields[hp_idx] = new_tag
        else:
            fields.append(new_tag)
    write("\t".join(fields) + "\n")